spring.application.name=products_app
spring.datasource.url=jdbc:mysql://localhost:3306/products_db
spring.datasource.username=root
spring.datasource.password=@Prince2427
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true